# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’
source 'https://github.com/roofstreet/cocoa.repo.git'
target 'RNVeery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNVeery
  pod 'Veery', ‘1.3.1’
 
end
